testing analysis of new format - can I load in all results from different metrics/datasets?

In [9]:
import pandas as pd
import json

In [10]:
def load_jsonl(path):
    """Load a JSONL file into a pandas DataFrame."""
    with open(path, "r", encoding="utf-8") as f:
        data = [json.loads(line) for line in f]
    return pd.DataFrame(data)

In [11]:
df = load_jsonl("/home/jayo/repos/MIRROR-Eval/results/testing/results.jsonl")

In [12]:
df

,input_id,input,metric,model_name,prompt,output,score,dataset,set1_avgcosine,set2_avgcosine,set1_chamfer,set2_chamfer
0,0,"{'src': 'We need bread on rainy days.', 'set1'...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale,"Based on the given criteria, I would give the ...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
1,0,"{'src': 'We need bread on rainy days.', 'set1'...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale_with_examples,Here are the scores for each set of sentences:...,-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
2,0,"{'src': 'We need bread on rainy days.', 'set1'...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category,"Based on the given criteria, I would assign th...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
3,0,"{'src': 'We need bread on rainy days.', 'set1'...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category_with_examples,"Based on the provided sentences, we can evalua...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
4,1,"{'src': 'She drove her car to space.', 'set1':...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale,"Set 1: [2.0, 1.0] - Good diversity\nSet 2: [1....",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
5,1,"{'src': 'She drove her car to space.', 'set1':...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale_with_examples,"Based on the given criteria, the following sco...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
6,1,"{'src': 'She drove her car to space.', 'set1':...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category,Here are the scores assigned to each set based...,-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
7,1,"{'src': 'She drove her car to space.', 'set1':...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category_with_examples,"Based on the given criteria, the set with more...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
8,2,"{'src': 'centre site', 'set1': ['A bustling sh...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale,Here are the scores assigned to each set of se...,-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
9,2,"{'src': 'centre site', 'set1': ['A bustling sh...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale_with_examples,"Set 1: [3, 2]\nThe sentence sets 1 explores a ...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
10,2,"{'src': 'centre site', 'set1': ['A bustling sh...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category,Here are the scores for the two sets of senten...,-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
11,2,"{'src': 'centre site', 'set1': ['A bustling sh...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category_with_examples,"Based on the given criteria, I would assign th...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
12,3,"{'src': 'life thing', 'set1': ['Love is a beau...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale,Here are the scores assigned to each set based...,-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
13,3,"{'src': 'life thing', 'set1': ['Love is a beau...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale_with_examples,"Based on the given criteria, I would assign a ...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
14,3,"{'src': 'life thing', 'set1': ['Love is a beau...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category,"Based on the given criteria, I would assign th...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
15,3,"{'src': 'life thing', 'set1': ['Love is a beau...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category_with_examples,"Based on the given criteria, the set with more...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
16,4,"{'src': 'eye give glisten nod', 'set1': ['With...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale,"Example Output: (5, 4)\nHere are the two sets ...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
17,4,"{'src': 'eye give glisten nod', 'set1': ['With...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale_with_examples,"Based on the given criteria, we can assign a s...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
18,4,"{'src': 'eye give glisten nod', 'set1': ['With...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category,"Based on the given criteria, I would assign th...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
19,4,"{'src': 'eye give glisten nod', 'set1': ['With...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category_with_examples,"Based on the provided sentences, we can make t...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
20,5,"{'src': 'band stand front perform', 'set1': ['...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale,"Sure, I can help you with that. Please provide...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
21,5,"{'src': 'band stand front perform', 'set1': ['...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale_with_examples,Set 1: 3.2\nExplanation: This set uses repetit...,-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
22,5,"{'src': 'band stand front perform', 'set1': ['...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category,Here are the scores for each set:\nSet 1: \n- ...,-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
23,5,"{'src': 'band stand front perform', 'set1': ['...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category_with_examples,Here are the scores for the two sets of senten...,-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN
24,0,"{'src': 'We need bread on rainy days.', 'set1'...",self-avgcosine,NaN,NaN,NaN,1,royal42/gcr-diversity,0.998677,0.980499,NaN,NaN
25,1,"{'src': 'She drove her car to space.', 'set1':...",self-avgcosine,NaN,NaN,NaN,0,royal42/gcr-diversity,0.991041,0.999876,NaN,NaN
26,2,"{'src': 'centre site', 'set1': ['A bustling sh...",self-avgcosine,NaN,NaN,NaN,1,royal42/gcr-diversity,0.999357,0.995992,NaN,NaN
27,3,"{'src': 'life thing', 'set1': ['Love is a beau...",self-avgcosine,NaN,NaN,NaN,0,royal42/gcr-diversity,0.999083,0.999569,NaN,NaN
28,4,"{'src': 'eye give glisten nod', 'set1': ['With...",self-avgcosine,NaN,NaN,NaN,1,royal42/gcr-diversity,0.994256,0.992869,NaN,NaN
29,5,"{'src': 'band stand front perform', 'set1': ['...",self-avgcosine,NaN,NaN,NaN,1,royal42/gcr-diversity,0.997658,0.997086,NaN,NaN
30,0,"{'src': 'We need bread on rainy days.', 'set1'...",chamfer,NaN,NaN,NaN,1,royal42/gcr-diversity,NaN,NaN,0.000781,0.009340
31,1,"{'src': 'She drove her car to space.', 'set1':...",chamfer,NaN,NaN,NaN,0,royal42/gcr-diversity,NaN,NaN,0.005241,0.000108
32,2,"{'src': 'centre site', 'set1': ['A bustling sh...",chamfer,NaN,NaN,NaN,1,royal42/gcr-diversity,NaN,NaN,0.000482,0.002592
33,3,"{'src': 'life thing', 'set1': ['Love is a beau...",chamfer,NaN,NaN,NaN,0,royal42/gcr-diversity,NaN,NaN,0.000814,0.000231
34,4,"{'src': 'eye give glisten nod', 'set1': ['With...",chamfer,NaN,NaN,NaN,1,royal42/gcr-diversity,NaN,NaN,0.002263,0.002963
35,5,"{'src': 'band stand front perform', 'set1': ['...",chamfer,NaN,NaN,NaN,1,royal42/gcr-diversity,NaN,NaN,0.001145,0.001760
36,0,"{'set1': ['1. ""Revolutionizing Renewables: New...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale,"Based on the evaluation criteria provided, the...",-1,royal42/mt-eval-creativity-demo,NaN,NaN,NaN,NaN
37,0,"{'set1': ['1. ""Revolutionizing Renewables: New...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale_with_examples,Here are the scores for each set:\nSet 1: \n- ...,-1,royal42/mt-eval-creativity-demo,NaN,NaN,NaN,NaN
38,0,"{'set1': ['1. ""Revolutionizing Renewables: New...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category,"Example Output: (Diversity_ScoreSET_1, Diversi...",-1,royal42/mt-eval-creativity-demo,NaN,NaN,NaN,NaN
39,0,"{'set1': ['1. ""Revolutionizing Renewables: New...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category_with_examples,"Based on the provided sentences, I am able to ...",-1,royal42/mt-eval-creativity-demo,NaN,NaN,NaN,NaN
40,1,"{'set1': ['The word ""car"" does not belong with...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale,"Example Output: (5 Points: Consistent Quality,...",-1,royal42/mt-eval-creativity-demo,NaN,NaN,NaN,NaN
41,1,"{'set1': ['The word ""car"" does not belong with...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale_with_examples,"Set 1: [3,2] - Quality Score: 3.2 - Diversity ...",-1,royal42/mt-eval-creativity-demo,NaN,NaN,NaN,NaN
42,1,"{'set1': ['The word ""car"" does not belong with...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category,"Based on the given sentences, I would assign t...",-1,royal42/mt-eval-creativity-demo,NaN,NaN,NaN,NaN
43,1,"{'set1': ['The word ""car"" does not belong with...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category_with_examples,Based on the evaluation of the two sets of sen...,-1,royal42/mt-eval-creativity-demo,NaN,NaN,NaN,NaN
44,0,"{'set1': ['1. ""Revolutionizing Renewables: New...",self-avgcosine,NaN,NaN,NaN,0,royal42/mt-eval-creativity-demo,0.952885,0.984190,NaN,NaN
45,1,"{'set1': ['The word ""car"" does not belong with...",self-avgcosine,NaN,NaN,NaN,0,royal42/mt-eval-creativity-demo,0.986987,0.991910,NaN,NaN
46,0,"{'set1': ['1. ""Revolutionizing Renewables: New...",chamfer,NaN,NaN,NaN,0,royal42/mt-eval-creativity-demo,NaN,NaN,0.016025,0.007126
47,1,"{'set1': ['The word ""car"" does not belong with...",chamfer,NaN,NaN,NaN,1,royal42/mt-eval-creativity-demo,NaN,NaN,0.002671,0.004360

In [14]:
# For each row, grab the "correct_answer" value from the dictionary in the input column, if it exists, and create a new column with it's value called "correct_answer"
df["correct_answer"] = df["input"].apply(lambda x: x.get("correct_answer") if isinstance(x, dict) else None)

In [15]:
df

,input_id,input,metric,model_name,prompt,output,score,dataset,set1_avgcosine,set2_avgcosine,set1_chamfer,set2_chamfer,correct_answer
0,0,"{'src': 'We need bread on rainy days.', 'set1'...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale,"Based on the given criteria, I would give the ...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,-1.0
1,0,"{'src': 'We need bread on rainy days.', 'set1'...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale_with_examples,Here are the scores for each set of sentences:...,-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,-1.0
2,0,"{'src': 'We need bread on rainy days.', 'set1'...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category,"Based on the given criteria, I would assign th...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,-1.0
3,0,"{'src': 'We need bread on rainy days.', 'set1'...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category_with_examples,"Based on the provided sentences, we can evalua...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,-1.0
4,1,"{'src': 'She drove her car to space.', 'set1':...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale,"Set 1: [2.0, 1.0] - Good diversity\nSet 2: [1....",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,0.0
5,1,"{'src': 'She drove her car to space.', 'set1':...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale_with_examples,"Based on the given criteria, the following sco...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,0.0
6,1,"{'src': 'She drove her car to space.', 'set1':...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category,Here are the scores assigned to each set based...,-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,0.0
7,1,"{'src': 'She drove her car to space.', 'set1':...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category_with_examples,"Based on the given criteria, the set with more...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,0.0
8,2,"{'src': 'centre site', 'set1': ['A bustling sh...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale,Here are the scores assigned to each set of se...,-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,0.0
9,2,"{'src': 'centre site', 'set1': ['A bustling sh...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale_with_examples,"Set 1: [3, 2]\nThe sentence sets 1 explores a ...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,0.0
10,2,"{'src': 'centre site', 'set1': ['A bustling sh...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category,Here are the scores for the two sets of senten...,-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,0.0
11,2,"{'src': 'centre site', 'set1': ['A bustling sh...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category_with_examples,"Based on the given criteria, I would assign th...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,0.0
12,3,"{'src': 'life thing', 'set1': ['Love is a beau...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale,Here are the scores assigned to each set based...,-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,0.0
13,3,"{'src': 'life thing', 'set1': ['Love is a beau...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale_with_examples,"Based on the given criteria, I would assign a ...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,0.0
14,3,"{'src': 'life thing', 'set1': ['Love is a beau...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category,"Based on the given criteria, I would assign th...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,0.0
15,3,"{'src': 'life thing', 'set1': ['Love is a beau...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category_with_examples,"Based on the given criteria, the set with more...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,0.0
16,4,"{'src': 'eye give glisten nod', 'set1': ['With...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale,"Example Output: (5, 4)\nHere are the two sets ...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,0.0
17,4,"{'src': 'eye give glisten nod', 'set1': ['With...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale_with_examples,"Based on the given criteria, we can assign a s...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,0.0
18,4,"{'src': 'eye give glisten nod', 'set1': ['With...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category,"Based on the given criteria, I would assign th...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,0.0
19,4,"{'src': 'eye give glisten nod', 'set1': ['With...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category_with_examples,"Based on the provided sentences, we can make t...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,0.0
20,5,"{'src': 'band stand front perform', 'set1': ['...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale,"Sure, I can help you with that. Please provide...",-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,0.0
21,5,"{'src': 'band stand front perform', 'set1': ['...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale_with_examples,Set 1: 3.2\nExplanation: This set uses repetit...,-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,0.0
22,5,"{'src': 'band stand front perform', 'set1': ['...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category,Here are the scores for each set:\nSet 1: \n- ...,-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,0.0
23,5,"{'src': 'band stand front perform', 'set1': ['...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category_with_examples,Here are the scores for the two sets of senten...,-1,royal42/gcr-diversity,NaN,NaN,NaN,NaN,0.0
24,0,"{'src': 'We need bread on rainy days.', 'set1'...",self-avgcosine,NaN,NaN,NaN,1,royal42/gcr-diversity,0.998677,0.980499,NaN,NaN,-1.0
25,1,"{'src': 'She drove her car to space.', 'set1':...",self-avgcosine,NaN,NaN,NaN,0,royal42/gcr-diversity,0.991041,0.999876,NaN,NaN,0.0
26,2,"{'src': 'centre site', 'set1': ['A bustling sh...",self-avgcosine,NaN,NaN,NaN,1,royal42/gcr-diversity,0.999357,0.995992,NaN,NaN,0.0
27,3,"{'src': 'life thing', 'set1': ['Love is a beau...",self-avgcosine,NaN,NaN,NaN,0,royal42/gcr-diversity,0.999083,0.999569,NaN,NaN,0.0
28,4,"{'src': 'eye give glisten nod', 'set1': ['With...",self-avgcosine,NaN,NaN,NaN,1,royal42/gcr-diversity,0.994256,0.992869,NaN,NaN,0.0
29,5,"{'src': 'band stand front perform', 'set1': ['...",self-avgcosine,NaN,NaN,NaN,1,royal42/gcr-diversity,0.997658,0.997086,NaN,NaN,0.0
30,0,"{'src': 'We need bread on rainy days.', 'set1'...",chamfer,NaN,NaN,NaN,1,royal42/gcr-diversity,NaN,NaN,0.000781,0.009340,-1.0
31,1,"{'src': 'She drove her car to space.', 'set1':...",chamfer,NaN,NaN,NaN,0,royal42/gcr-diversity,NaN,NaN,0.005241,0.000108,0.0
32,2,"{'src': 'centre site', 'set1': ['A bustling sh...",chamfer,NaN,NaN,NaN,1,royal42/gcr-diversity,NaN,NaN,0.000482,0.002592,0.0
33,3,"{'src': 'life thing', 'set1': ['Love is a beau...",chamfer,NaN,NaN,NaN,0,royal42/gcr-diversity,NaN,NaN,0.000814,0.000231,0.0
34,4,"{'src': 'eye give glisten nod', 'set1': ['With...",chamfer,NaN,NaN,NaN,1,royal42/gcr-diversity,NaN,NaN,0.002263,0.002963,0.0
35,5,"{'src': 'band stand front perform', 'set1': ['...",chamfer,NaN,NaN,NaN,1,royal42/gcr-diversity,NaN,NaN,0.001145,0.001760,0.0
36,0,"{'set1': ['1. ""Revolutionizing Renewables: New...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale,"Based on the evaluation criteria provided, the...",-1,royal42/mt-eval-creativity-demo,NaN,NaN,NaN,NaN,NaN
37,0,"{'set1': ['1. ""Revolutionizing Renewables: New...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale_with_examples,Here are the scores for each set:\nSet 1: \n- ...,-1,royal42/mt-eval-creativity-demo,NaN,NaN,NaN,NaN,NaN
38,0,"{'set1': ['1. ""Revolutionizing Renewables: New...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category,"Example Output: (Diversity_ScoreSET_1, Diversi...",-1,royal42/mt-eval-creativity-demo,NaN,NaN,NaN,NaN,NaN
39,0,"{'set1': ['1. ""Revolutionizing Renewables: New...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category_with_examples,"Based on the provided sentences, I am able to ...",-1,royal42/mt-eval-creativity-demo,NaN,NaN,NaN,NaN,NaN
40,1,"{'set1': ['The word ""car"" does not belong with...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale,"Example Output: (5 Points: Consistent Quality,...",-1,royal42/mt-eval-creativity-demo,NaN,NaN,NaN,NaN,NaN
41,1,"{'set1': ['The word ""car"" does not belong with...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,scale_with_examples,"Set 1: [3,2] - Quality Score: 3.2 - Diversity ...",-1,royal42/mt-eval-creativity-demo,NaN,NaN,NaN,NaN,NaN
42,1,"{'set1': ['The word ""car"" does not belong with...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category,"Based on the given sentences, I would assign t...",-1,royal42/mt-eval-creativity-demo,NaN,NaN,NaN,NaN,NaN
43,1,"{'set1': ['The word ""car"" does not belong with...",llm-as-a-judge,Qwen/Qwen1.5-0.5B-Chat,category_with_examples,Based on the evaluation of the two sets of sen...,-1,royal42/mt-eval-creativity-demo,NaN,NaN,NaN,NaN,NaN
44,0,"{'set1': ['1. ""Revolutionizing Renewables: New...",self-avgcosine,NaN,NaN,NaN,0,royal42/mt-eval-creativity-demo,0.952885,0.984190,NaN,NaN,NaN
45,1,"{'set1': ['The word ""car"" does not belong with...",self-avgcosine,NaN,NaN,NaN,0,royal42/mt-eval-creativity-demo,0.986987,0.991910,NaN,NaN,NaN
46,0,"{'set1': ['1. ""Revolutionizing Renewables: New...",chamfer,NaN,NaN,NaN,0,royal42/mt-eval-creativity-demo,NaN,NaN,0.016025,0.007126,NaN
47,1,"{'set1': ['The word ""car"" does not belong with...",chamfer,NaN,NaN,NaN,1,royal42/mt-eval-creativity-demo,NaN,NaN,0.002671,0.004360,NaN